route/link/sriov: fix initializing vlans in rtnl_link_sriov_clone()
  Error: SIZEOF_MISMATCH (CWE-398):
  libnl-3.6.0/lib/route/link/sriov.c:125: suspicious_sizeof: Passing argument "dst_vlan_info" of type "nl_vf_vlan_info_t *" and argument "dst_vlans->size * 8UL /* sizeof (dst_vlan_info) */"
  libnl-3.6.0/lib/route/link/sriov.c:125: remediation: Did you intend to use "sizeof (*dst_vlan_info)" instead of "sizeof (dst_vlan_info)"?
  #  123|   			dst_vlan_info = dst_vlans->vlans;
  #  124|   			memcpy(dst_vlans, src_vlans, sizeof(nl_vf_vlans_t));
  #  125|-> 			memcpy(dst_vlan_info, src_vlan_info,
  #  126|   			       dst_vlans->size * sizeof(dst_vlan_info));
  #  127|   			d_vf->vf_vlans = dst_vlans;

Fixes: a59cab6d0b0f ('lib/route: SRIOV Clone Support')