all: avoid coverity warnings about assigning variable but not using it
Workaround coverity warnings like:

  Error: CLANG_WARNING:
  libnl-3.6.0/lib/netfilter/exp.c:428:7: warning[deadcode.DeadStores]: Although the value stored to 'err' is used in the enclosing expression, the value is never actually read from 'err'
  #  426|   	}
  #  427|···
  #  428|-> 	if ((err = nfnl_exp_build_tuple(msg, exp, CTA_EXPECT_NAT)) < 0)
  #  429|   		goto nla_put_failure;
  #  430|···