route/tc: ensure not string truncation in rtnl_tc_set_kind()
The compiler warns:

  In function ‘rtnl_tc_set_kind’,
      inlined from ‘rtnl_tc_msg_parse’ at lib/route/tc.c:81:2:
  lib/route/tc.c:532:2: error: ‘strncpy’ output may be truncated copying 31 bytes from a string of length 31 [-Werror=stringop-truncation]
    532 |  strncpy(tc->tc_kind, kind, sizeof(tc->tc_kind) - 1);
        |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Now, there are two choices: either accept the truncation
or rejecting it.

While rejecting it is a change in behavior and API, I don't think that
any caller actually relied on that. That is because such "kind" name would
be invalid anyway (and rejected from kernel too).

So, tighten up the API and check for a suitable string length.

Also, use _nl_strncpy() instead of strncpy(). Note that that doesn't suppress
the warning, it merely (also) adds an _nl_assert() for something that already
shouldn't happen.