build: suppress "-Wno-unused-but-set-variable" when building grammar
bison/flex generates rather ugly C code. Need to suppress this warning.

    lib/route/cls/ematch_syntax.c:1368:9: error: variable 'ematch_nerrs' set but not used [-Werror,-Wunused-but-set-variable]
     1368 |     int yynerrs = 0;
          |         ^
    lib/route/cls/ematch_syntax.c:72:25: note: expanded from macro 'yynerrs'
       72 | #define yynerrs         ematch_nerrs
          |                         ^
    1 error generated.

Had one job.