socket: workaround undefined behavior coverity warning in generate_local_port()
Coverity thinks that we can bitshift by a negative number:

  Error: BAD_SHIFT (CWE-682):
  libnl-3.6.0/lib/socket.c:69: return_constant: Function call "time(NULL)" may return -1.
  libnl-3.6.0/lib/socket.c:69: assignment: Assigning: "t" = "time(NULL)". The value of "t" is now 4294967295.
  libnl-3.6.0/lib/socket.c:73: assignment: Assigning: "idx_state" = "t ^ (t >> 16) ^ 0x3047U". The value of "idx_state" is now 12359.
  libnl-3.6.0/lib/socket.c:78: assignment: Assigning: "n" = "idx_state". The value of "n" is now -53177.
  libnl-3.6.0/lib/socket.c:94: assignment: Assigning: "n" = "(n + 13) % 32". The value of "n" is now -12.
  libnl-3.6.0/lib/socket.c:95: negative_shift: In expression "used_ports_map[i] >> n", shifting by a negative amount has undefined behavior.  The shift amount, "n", is -12.
  #   93|   		for (m = 0; m < 32; m++) {
  #   94|   			n = (n + 13) % 32;
  #   95|-> 			if (1UL & (used_ports_map[i] >> n))
  #   96|   				continue;
  #   97|···

  Error: BAD_SHIFT (CWE-682):
  libnl-3.6.0/lib/socket.c:69: return_constant: Function call "time(NULL)" may return -1.
  libnl-3.6.0/lib/socket.c:69: assignment: Assigning: "t" = "time(NULL)". The value of "t" is now 4294967295.
  libnl-3.6.0/lib/socket.c:73: assignment: Assigning: "idx_state" = "t ^ (t >> 16) ^ 0x3047U". The value of "idx_state" is now 12359.
  libnl-3.6.0/lib/socket.c:78: assignment: Assigning: "n" = "idx_state". The value of "n" is now -53177.
  libnl-3.6.0/lib/socket.c:94: assignment: Assigning: "n" = "(n + 13) % 32". The value of "n" is now -12.
  libnl-3.6.0/lib/socket.c:98: negative_shift: In expression "1UL << n", shifting by a negative amount has undefined behavior.  The shift amount, "n", is -12.
  #   96|   				continue;
  #   97|···
  #   98|-> 			used_ports_map[i] |= (1UL << n);
  #   99|   			n += (i * 32);
  #  100|···

I don't see how that can happen. "n" was type int (32 bit, in practice),
but was initialized from an uint16_t (idx_state). Thus  the number is positive
and small. Then we keep adding small numbers and modulo 32.

Anyway, try to silence the warning by using unsigned.