lib: remove unused assignment in nl_addr_parse()
Coverity warns about this. Avoid it.

  Error: CLANG_WARNING: [#def3]
  libnl-3.8.0/lib/addr.c:324:3: warning[deadcode.DeadStores]: Value stored to 'len' is never read
  #  322|   	    !strcasecmp(str, "any")) {
  #  323|
  #  324|-> 		len = 0;
  #  325|
  #  326|   		switch (hint) {